# Site settings
title: Blog
tagline: ~
description: This is a blog for u guys
image: /assets/images/site-image.png
url: https://sampada.lol
github_url: https://github.com/sampada-nepal
author: Sampada Nepal
lang: en-US
logo: /favicon.png

# Build settings
remote_theme: meebuhs/arco
plugins:
  - jekyll-sitemap
